mutation ($content: String!, $parentId: ID, $postId: ID!) {
  commentPost (content: $content, parentId: $parentId, postId: $postId) {
    comment {
      author {
        avatarUrl
        email
        handle
        id
        name
      }
      children {
        author {
          avatarUrl
          email
          handle
          id
          title
          name
        }
        children {
          content
          id
        }
        content
        id
      }
      content
      id
    }
    errors
  }
}
