mutation ($commentId: ID!) {
  upvoteComment (commentId: $commentId) {
    comment {
      author {
        avatarUrl
        email
        handle
        id
        name
      }
      children {
        author {
          avatarUrl
          email
          handle
          id
          name
        }
        children {
          content
          hasUpvoted
          id
          upvoteCount
        }
        content
        hasUpvoted
        id
        upvoteCount
      }
      content
      hasUpvoted
      id
      upvoteCount
    }
    errors
  }
}
