mutation ($body: String!, $cover: Upload, $products: [ID], $skills: [ID], $slug: String!, $title: String!) {
  createPost (body: $body, cover: $cover, products: $products, skills: $skills, slug: $slug, title: $title) {
    errors
    post {
      author {
        avatarUrl
        email
        handle
        id
        name
        role
        title
      }
      body
      comments {
        author {
          avatarUrl
          email
          handle
          id
          name
          role
          title
        }
        children {
          author {
            avatarUrl
            email
            handle
            id
            name
            role
            title
          }
          children {
            content
            hasUpvoted
            id
            upvoteCount
          }
          content
          hasUpvoted
          id
          upvoteCount
        }
        content
        hasUpvoted
        id
        upvoteCount
      }
      coverUrl
      hasLiked
      id
      likesCount
      products {
        description
        id
        name
        slug
      }
      skills {
        description
        id
        name
        slug
      }
      slug
      title
    }
  }
}
