mutation ($postId: ID!) {
  likePost (postId: $postId) {
    errors
    post {
      author {
        avatarUrl
        email
        handle
        id
        name
      }
      body
      comments {
        author {
          avatarUrl
          email
          handle
          id
          name
        }
        children {
          author {
            avatarUrl
            email
            handle
            id
            name
          }
          children {
            content
            id
          }
          content
          id
        }
        content
        id
      }
      skills {
        name
        id
      }
      coverUrl
      hasLiked
      id
      likesCount
      slug
      title
    }
  }
}
