query postSlug ($slug: String) {
  postSlug (slug: $slug) {
    author {
      avatarUrl
      email
      handle
      id
      name
      role
      title
      skills {
        description
        id
        name
        slug
      }
    }
    body
    comments {
      author {
        avatarUrl
        email
        handle
        id
        name
        role
        title
      }
      children {
        author {
          avatarUrl
          email
          handle
          id
          name
          role
          title
        }
        children {
          content
          hasUpvoted
          id
          upvoteCount
          inserted_at
        }
        content
        hasUpvoted
        id
        upvoteCount
        inserted_at
      }
      content
      hasUpvoted
      id
      inserted_at
      upvoteCount
    }
    coverUrl
    hasLiked
    id
    likesCount
    products {
      description
      id
      name
      slug
    }
    skills {
      description
      id
      name
      slug
    }
    slug
    title
  }
}
