mutation ($body: String!, $cover: Upload, $skills: [ID], $slug: String!, $title: String!) {
  createPost (body: $body, cover: $cover, skills: $skills, slug: $slug, title: $title) {
    errors
    post {
      author {
        avatarUrl
        dribbbleUrl
        email
        githubUrl
        handle
        id
        name
        websiteUrl
      }
      body
      comments {
        author {
          avatarUrl
          dribbbleUrl
          email
          githubUrl
          handle
          id
          name
          websiteUrl
        }
        children {
          author {
            avatarUrl
            dribbbleUrl
            email
            githubUrl
            handle
            id
            name
            websiteUrl
          }
          children {
            content
            id
          }
          content
          id
        }
        content
        id
      }
      coverUrl
      hasLiked
      id
      likesCount
      slug
      title
    }
  }
}
