mutation ($postId: ID!) {
  likePost (postId: $postId) {
    errors
    post {
      author {
        avatarUrl
        dribbbleUrl
        email
        githubUrl
        handle
        id
        name
        websiteUrl
      }
      body
      comments {
        author {
          avatarUrl
          dribbbleUrl
          email
          githubUrl
          handle
          id
          name
          websiteUrl
        }
        children {
          author {
            avatarUrl
            dribbbleUrl
            email
            githubUrl
            handle
            id
            name
            websiteUrl
          }
          children {
            content
            id
          }
          content
          id
        }
        content
        id
      }
      skills {
        name
        id
      }
      coverUrl
      hasLiked
      id
      likesCount
      slug
      title
    }
  }
}
