mutation($email: String!, $password: String!) {
    login (email: $email, password: $password) {
        token
        user {
            avatarUrl
            dribbbleUrl
            email
            githubUrl
            id
            name
            websiteUrl
        }
    }
}
