query ($slug: String!) {
    getPostBySlug(slug: $slug) {
        author {
            avatarUrl
            dribbbleUrl
            email
            githubUrl
            handle
            id
            name
            websiteUrl
        }
        body
        description
        id
        cover_url
        skills {
            description
            id
            name
            slug
        }
        slug
        title
    }
}
