query posts {
  posts {
    author {
      avatarUrl
      email
      handle
      id
      name
      role
      title
    }
    body
    comments {
      author {
        avatarUrl
        email
        handle
        id
        name
        role
        title
      }
      children {
        author {
          avatarUrl
          email
          handle
          id
          name
          role
          title
        }
        children {
          content
          hasUpvoted
          id
          upvoteCount
        }
        content
        hasUpvoted
        id
        upvoteCount
      }
      content
      hasUpvoted
      id
      upvoteCount
    }
    coverUrl
    hasLiked
    id
    likesCount
    products {
      description
      id
      name
      slug
    }
    skills {
      description
      id
      name
      slug
    }
    slug
    title
  }
}
