query ($slug: String) {
  postSlug (slug: $slug) {
    author {
      avatarUrl
      dribbbleUrl
      email
      githubUrl
      handle
      id
      name
      websiteUrl
    }
    body
    comments {
      author {
        avatarUrl
        dribbbleUrl
        email
        githubUrl
        handle
        id
        name
        websiteUrl
      }
      children {
        author {
          avatarUrl
          dribbbleUrl
          email
          githubUrl
          handle
          id
          name
          websiteUrl
        }
        children {
          content
          hasUpvoted
          id
          upvoteCount
        }
        content
        hasUpvoted
        id
        upvoteCount
      }
      content
      hasUpvoted
      id
      upvoteCount
    }
    coverUrl
    hasLiked
    id
    likesCount
    skills {
      description
      id
      name
      slug
    }
    slug
    title
  }
}
