mutation ($avatar: Upload, $email: String!, $handle: String, $name: String!, $password: String!, $role: Role!, $title: String!) {
  register (avatar: $avatar, email: $email, handle: $handle, name: $name, password: $password, role: $role, title: $title) {
    errors
    user {
      avatarUrl
      email
      handle
      id
      name
      role
      title
    }
  }
}
