mutation ($commentId: ID!) {
  upvoteComment (commentId: $commentId) {
    comment {
      author {
        avatarUrl
        dribbbleUrl
        email
        githubUrl
        handle
        id
        name
        websiteUrl
      }
      children {
        author {
          avatarUrl
          dribbbleUrl
          email
          githubUrl
          handle
          id
          name
          websiteUrl
        }
        children {
          content
          hasUpvoted
          id
          upvoteCount
        }
        content
        hasUpvoted
        id
        upvoteCount
      }
      content
      hasUpvoted
      id
      upvoteCount
    }
    errors
  }
}
