mutation ($email: String!, $password: String!) {
  login (email: $email, password: $password) {
    accessToken
    errors
    user {
      avatarUrl
      email
      handle
      id
      name
      role
      title
    }
  }
}
